modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="dragonblockbeyond" #mandatory
version="0.1" #mandatory
 # A display name for the mod
displayName="DragonBlock Beyond" #mandatory
authors="FireTamer, MatyRobert, Pierre the Wise, Echo,Nyfaria" #optional
description='''
The DragonBlock mod of the future.... hopefully.
'''
[[dependencies.dragonblockbeyond]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonblockbeyond]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
